### ISSUE TITLE
x86 version of this tool

### ISSUE THREAD

**Issue by IL2** [fiddyschmitt/clonezilla-util#1]
Hello Fidel, Thank you very much for making this tool available!
Any chance of x86 version?

**Comment by fiddyschmitt** [comment]
Thanks IL2, my pleasure :)

Absolutely, I'll compile an x86 version today. I haven't tried it in 32-bit mode so not sure how well it would work, but hopefully .NET does the right things for it to run smoothly. You'll be the guinea pig :)

**Comment by fiddyschmitt** [comment]
Actually the program is compiled as 'Any CPU', which supports both x86 and x64.
But that doesn't apply to the tools I've bundled (gztool and 7-Zip) which are both x64 only.

Could you please attach a screenshot of what you are seeing?

I'll make sure to bundle x86 version of the two tools in the next release (today).

Thank you,
Fidel

**Comment by fiddyschmitt** [comment]
Hi IL2,

Just published a new version, and this time included an x86 version. Please let me know how it goes.

Cheers,
Fidel

**Comment by fiddyschmitt** [comment]
Hi IL2,

Just published a new version, and this time included an x86 version. Please let me know how it goes.

Cheers,
Fidel

**Comment by IL2** [comment]
Hello Fidel, v1.5 now starts on x86 w/o issues.
[00:46:11 INF] clonezilla-util v1.5
clonezilla-util 1.0.0
Copyright (C) 2022 clonezilla-util
I'll try to mount the image and report back.
Thanks!

**Comment by IL2** [comment]
Hello Fidel, finally could find some time to check v1.5.
In brief I fiound it working for cases in bold.
extract-partition-image and mount operations were checked against different clonezilla modes (beginner, expert: partclone, ntfsclone, dd, partimage) with and w/o compression with two different cloenzilla versions (2015 and 2019).

Results are in the table below and reports attached:
[clonezilla-util.v1.5.win-x86.zip](https://github.com/fiddyschmitt/clonezilla-util/files/8103228/clonezilla-util.v1.5.win-x86.zip)
image mode	clonezilla	operation	result
beginner gzip	2015	extract	GzDecompressor requires a partition cache. Not yet implemented.
**beginner gzip	2019	extract	OK**
beginner gzip	2015	mount	GzDecompressor requires a partition cache. Not yet implemented.
beginner gzip	2019	mount	GzDecompressor requires a partition cache. Not yet implemented.
dd gzip	2015	extract	GzDecompressor requires a partition cache. Not yet implemented.
**dd uncomp	2015	mount	OK**
**dd uncomp	2019	mount	OK**
ntfsclone gzip	2015	extract	GzDecompressor requires a partition cache. Not yet implemented.
ntfsclone uncomp	2015	mount	Cannot open the file as archive
ntfsclone uncomp	2019	mount	Cannot open the file as archive
partclone lzip	2015	extract	Cannot open the file as archive
partclone lzip	2015	mount	Cannot open the file as archive
partclone uncomp	2015	mount	Cannot open the file as archive
**partclone uncomp	2019	mount	OK**
partimage gzip	2015	extract	GzDecompressor requires a partition cache. Not yet implemented.
partimage uncomp	2015	mount	Cannot open the file as archive
partimage uncomp	2019	mount	Cannot open the file as archive

**Comment by fiddyschmitt** [comment]
Oh wow! Thanks so much for taking the time to do this. I'll work through the list.
Thanks again

**Comment by IL2** [comment]
Hi, it was revelating that mounting has worked out with the simplest clonezilla 2015 dd image!
I was going through these cases o undestand what modes can be used in conjunction with your tool.

Observations:
- result of extract/mount depends on the type of input argument - clonezilla folder or image file
- runs with folder as argument failed in all cases except extracting clonezilla 2019 beginner image in 2019\OK_extract_beginner_folder.txt
- mount was OK with uncompressed dd 2015/2019 and partclone 2019 clonezilla images, extracted clonezilla 2019 beginner image!
- mount in other cases failed either with GzDecompressor, or 7-zip "Cannot open as arrchive", or "Could not determine compression used by partition", or "Error while opening partition" errors. I didn't put in the table above results with folder as input argument except positive extracing clonezilla 2019 beginner image
- there is no x86 version of ext\gztool in v1.5 and v1.5.3

I guess results might have been improved in v1.5.3 due to https://github.com/fiddyschmitt/clonezilla-util/commit/e47529b0643941010b98e2c14a05949f02670083

Reports are named as <CZ version>\<result>_<operation>_<image>_<type of input argument>.txt
2019\err_extract_beginner_img.txt
2019\OK_extract_beginner_folder.txt

**Comment by fiddyschmitt** [comment]
So good! Thank you!
