### ISSUE TITLE
Waiting for M: to be available.

### ISSUE THREAD

**Issue by anatolbaskak** [fiddyschmitt/clonezilla-util#15]
Hi,
I tried to mount a partition from Clonezilla repository, and after successfull caching it's stuck on:

> [16:28:21 INF] Waiting for M: to be available.

The M: letter is free.
![image](https://user-images.githubusercontent.com/114681079/193073485-362da9cb-7964-475d-aab2-cc4fd9a5982b.png)

**Comment by fiddyschmitt** [comment]
Hello!

Thanks for reaching out.

Could you please confirm you installed [this version](https://github.com/dokan-dev/dokany/releases/tag/v1.5.1.1000) of the Dokan driver?

If you've already tried that version, perhaps try this alternative command:
`clonezilla-util.exe extract-partition-image --input <clonzilla folder> --output <folder to extract to>`

Then use 7-Zip to open the extracted file.

Please let me know how you go :)

Cheers,
Fidel

**Comment by anatolbaskak** [comment]
Hi!
Thanks for prompt reply.
Indeed I didn't catch the memo about the particular version.
It works now. Sorry for confusion. Thanks for great tool.
Cheers!

**Comment by fiddyschmitt** [comment]
That's great! My pleasure :D
