### ISSUE TITLE
Reading partclone content map...

### ISSUE THREAD

**Issue by Pitfour** [fiddyschmitt/clonezilla-util#16]
After adding an inf file thanks to another post, a 300GB file has cached successfully in 3 hrs. Now stuck on reading partclone image map. HD and RAM @ 100% , CPU at 5%. Can I know how long this process might take...or speed it up from the cache?

**Comment by Pitfour** [comment]
After 24h, now states: waiting for L:\ to be available.

**Comment by fiddyschmitt** [comment]
Hi Pitfour, 

Thanks for following up (and your patience!).

Could you please confirm you have this specific version ([1.5.1.1000](https://github.com/dokan-dev/dokany/releases/tag/v1.5.1.1000)) of Dokan installed?

**Comment by Pitfour** [comment]
Mmm I was trying to be too clever and used the latest version. Will try again with 1.5.1.1000.

**Comment by fiddyschmitt** [comment]
Haha np, thanks :)

**Comment by Pitfour** [comment]
Util used existing cache but after several hours: Waiting for L:\ to be available then ERR No partition to mount, exiting.

**Comment by fiddyschmitt** [comment]
Thanks. Could you please let me know the command you used?

**Comment by fiddyschmitt** [comment]
Thanks,
Could you please post the contents of the `clonezilla-img` file, or a screenshot of the files in your clonezilla folder?

**Comment by Pitfour** [comment]
[clonezilla-img.txt](https://github.com/fiddyschmitt/clonezilla-util/files/9854949/clonezilla-img.txt)
![CloneZ folder](https://user-images.githubusercontent.com/116266449/197617109-5e9ce683-55d9-41d8-a7f5-24c7b4e619e2.PNG)

F
Files as requested.

Robin F London

**Comment by fiddyschmitt** [comment]
Thanks Robin, much appreciated.
That all looks good.

Could you please post the most recent file from the clonezilla-util `logs` folder?

Also, could you please try the following, which tries to extract sda4 directly?
`clonezilla-util.exe extract-partition-image --input "C:\your_path\Desktop\2022-10-05-15-img-Test\sda4.ntfs-ptcl-img.gz.aa" --output "C:\Temp"`

You might then be able to use 7-Zip to open the file in `C:\Temp`

Thanks again for your help with this!

Cheers,
Fidel
