### ISSUE TITLE
Cannot open vfat partition

### ISSUE THREAD

**Issue by julitadpo** [fiddyschmitt/clonezilla-util#2]
Hello Fidel,

i´m using your tool, but i find a problem, maybe you can help me. I´ve install 7zip, Dokan Driver, and unzip clonezilla-util in a folder. I run the command "clonezilla-util.exe mount --input imagefolder --mount L:\", it unzip everything and at the end y get the next screenshot,and the new drive doesn´t appear,

Can you help me? I don´t know if i have to install more librarys(i´ve already install runtime .net). Im runing windows 10, x64, virtual machine.
![WhatsApp Image 2022-01-26 at 12 15 03](https://user-images.githubusercontent.com/98461056/151155106-5717e4fc-b791-40f1-a14f-7e8198e964ae.jpeg)

Thankyou in advance.Regards.

**Comment by fiddyschmitt** [comment]
Hi julitadpo,

Happy to help!

Firstly, you don't need to install 7-Zip, it comes bundled with clonezilla-util. You just need the Dokan driver as you've installed.

It looks like the error happens when processing the second partition (sda2). Could you please see if sda1 mounts okay?

Please run your same command with `-p sda1` and please let me know if it mounts correctly to L:\

**Comment by fiddyschmitt** [comment]
I'm off to bed now, but if you get a chance, please also post the contents of a file called `dev-fs.list` in your Clonezilla folder. Thanks!

**Comment by julitadpo** [comment]
Hello,

Thank you, with the command -p sda1 works fine, probably the problem is the Clonezilla image. Im gonna test another image and i´ll let you know.

**Comment by fiddyschmitt** [comment]
You're welcome :)
Could you please look inside `dev-fs.list` and tell me what format is used by `sda1` and `sda2`?

**Comment by julitadpo** [comment]
sda1 ntfs
sda2 vfat
sda3 MS_Reserved_Partition
sda4 ntfs

**Comment by fiddyschmitt** [comment]
Thank you! I'll see if I can reproduce it

**Comment by fiddyschmitt** [comment]
Hi julitadpo,

I just released v1.5.3 which gracefully handles partitions that 7-Zip can't inspect.

I'd still like to replicate the issue; was it Windows XP that is stored in your Clonezilla archive?

Thanks,
Fidel

**Comment by julitadpo** [comment]
Hi¡¡

It´s Windows 10 LTSC x64

**Comment by julitadpo** [comment]
By the way, "mount-as-image" doesn´t work in v1.5, Verb is not recognized.

**Comment by fiddyschmitt** [comment]
Oh thanks! I had forgotten to update the readme. It's now `mount-as-image-files`
