### ISSUE TITLE
Open Clonezilla archive without Info-img-id.txt

### ISSUE THREAD

**Issue by CasseThor** [fiddyschmitt/clonezilla-util#3]
Hello,
i have a clonezilla file but without Info-img-id.txt ?
Can i bypass this to create .img ?

Thanks

**Comment by fiddyschmitt** [comment]
Hi Casse,

You could create `Info-img-id.txt` by hand. Here is the content it could contain:

```
# This checksum is only for identifying the image. Created by the command: sha512sum clonezilla-img
IMG_ID=0b1d6cdef1095ced977490d2454c3f76e4a9926d0b59cdb0f9a35b9d045a0c55673d94ab20e58c1633e14e62dff435757e50aca39d3a921f0e2477253c464b77
```

That should let the program continue a bit further.

It's unusual that you don't have that info file. Could you please post the content of these files:

`Info-packages.txt`
`clonezilla-img`

Thank you,
Fidel

**Comment by CasseThor** [comment]
Image was saved by these Clonezilla-related packages:
 drbl-2.23.1-drbl1 clonezilla-3.24.7-drbl1 partclone-0.2.89-drbl1 drbl-chntpw-20110511-1drbl util-linux-2.29-1 gdisk-1.0.1-1
Saved by clonezilla-live-2.5.0-5-amd64.

and i dont have clonezilla-img

Thanks

**Comment by fiddyschmitt** [comment]
Thanks Casse
