### ISSUE TITLE
Could not find file '\Info-img-id.txt'

### ISSUE THREAD

**Issue by walker164** [fiddyschmitt/clonezilla-util#34]
When trying to mount the folder, it seems like there's supposed to be another txt file called Info-img-id.txt that isn't there. I'm seeing a "Could not find file" error. Is there a way around this? I tried to mount directly with the command `clonezilla-util.exe mount-as-image-files --input "C:\Users\sgray\Desktop\clonezilla-util.v2.0.4.win-x64\JohnDeere\sda2.ntfs-ptcl-img.gz.aa" --mount L:\` and it ran through the entire extraction process, but then failed at the end. I'm assuming it failed because that sda2 partition is broken into two pieces (files "sda2.ntfs-ptcl-img.gz.aa" and "sda2.ntfs-ptcl-img.gz.ab") but from the guide, I wasn't sure if there's a way to tell the app that the partition has multiple files. I'm assuming that might be what the Info-img-id text file might be for....

Thanks for your help on this! :)

![Screenshot 2023-04-20 100227](https://user-images.githubusercontent.com/5420153/233408362-09db6e03-b6f0-4a54-90b2-bcfe5a7210c7.png)
![Screenshot 2023-04-20 100422](https://user-images.githubusercontent.com/5420153/233408367-7fb9f473-4ab9-4fb0-a04b-2d70e14017e7.png)

**Comment by walker164** [comment]
I ended up using clonezilla to clone the image onto a random unused laptop and then pulled the hard drive to get the files I needed 🤷‍♀️

**Comment by fiddyschmitt** [comment]
Hi Walker,

Sorry for the late response and that you had to resort to a full extraction!

`Info-img-id.txt` is used to work out a unique Id for the archive, for caching purposes. The content doesn't really matter, so you could use [this one](https://github.com/fiddyschmitt/clonezilla-util/files/11360398/Info-img-id.txt) and it should work. It's very curious that your archive didn't have one. Could you please upload your `clonezilla-img` so I can see what might have happened?

Thanks!
Fidel
