### ISSUE TITLE
sda1.img : Cannot open the file as archive - Win11 - probably 7zip lib problem

### ISSUE THREAD

**Issue by WebMacke** [fiddyschmitt/clonezilla-util#35]
Thanks for your nice tool. It looks it is exact what I am looking for, but unfortunately it is not working for me. 

"PS C:\portableApps\clonezilla-util> .\clonezilla-util.exe mount --input D:\2023-05-08-1315-img-rescuezilla-kay-kevin-disk2\ --mount L:\
[03:59:27 INF] clonezilla-util v2.0.4
[03:59:28 INF] [] [sda1] Finding optimal decompressor (seekable/sequential)
[03:59:38 INF] [] [sda1] Loading partition information
[03:59:38 INF] [] [sda1] Reading partclone content map
[03:59:40 INF] Waiting for L:\ to be available.
[03:59:40 INF] [] [sda1] Retrieving a list of files.
[03:59:40 ERR] C:\portableApps\clonezilla-util\ext\7-Zip\win-x64\7z.exe l "L:\18b4297b-9b2e-4270-8124-dc0d4069c9af - Temp\c7a3abc4-3bab-4055-8807-377f577f0426\sda1.img"
Process encountered errors:
ERROR: L:\18b4297b-9b2e-4270-8124-dc0d4069c9af - Temp\c7a3abc4-3bab-4055-8807-377f577f0426\sda1.img : Cannot open the file as archive

[03:59:40 ERR] [] [sda1] The image file for this partition (L:\18b4297b-9b2e-4270-8124-dc0d4069c9af - Temp\c7a3abc4-3bab-4055-8807-377f577f0426\sda1.img) is not considered an archive by 7-Zip. Returning empty file list.
[03:59:40 INF] Mounting complete. Mounted to: L:\
Running. Press Enter to exit."

The clonezilla-img files on a pastebin like service:
disk1 with gzip compression: https://0.0g.gg/?bb7c677db873f108#FMHF7y7vHv6UrzUQYVTD4N7BVKab27eerRYX3YBi9f2a
disk2 without compression: https://0.0g.gg/?cdaa9657002145ac#52dW4bsQ6bBydfhV7enJhSb65ksBkXJURnNhcrAphz3F

**Comment by WebMacke** [comment]
Same Error, when i use the following command and try to open sda1.img with 7-zip, NanaZip or PeaZip.

.\clonezilla-util.exe mount-as-image-files --input D:\2023-05-08-1315-img-rescuezilla-kay-kevin-disk2\ --mount L:\

PeaZip returned: no match - additional info: Archive may not be valid (due missing, corrupted, or out of
standard data), it is possible to run Test for detailed information.
If archiveis table of content is encrypted, password is needed
before browsing it.

Can it be that between creation of the clonezilla image and now the file has been coruppted? I could probably compare current checksum and the one created after the initial backup. The image creation was successfull and with resuezilla i could also browse everything. The backuped harddrives where very old. The current ones are fine. Just checked with CrystalDiskInfo.

**Comment by fiddyschmitt** [comment]
Thanks Mack,

Could you please send me a screenshot of the beginning of sda1.img, using a Hex Editor. If you don't have one, [HxD](https://mh-nexus.de/en/hxd/) is good.

Thanks!
Fidel

**Comment by Jaynator495** [comment]
I realize this is a closed issue, but I am also having this issue. the beginning is basically all 0's (I saved it as an uncompressed image, if it helps) 
![image](https://github.com/fiddyschmitt/clonezilla-util/assets/13039635/8fe8e5e7-a97b-4405-a389-be5d6e2e15e0)

I attempted to use this tool right after creating the backup, and clonezilla did say it was restorable
