### ISSUE TITLE
Add support for uncompressed partition

### ISSUE THREAD

**Issue by swm123456** [fiddyschmitt/clonezilla-util#4]
I have some uncompressed partitions: 
> mmcblk0p1.vfat-ptcl-img.uncomp.aa

> mmcblk0p3.ext4-ptcl-img.uncomp.aa

And I get exception:

> [15:08:53 INF] clonezilla-util v1.5.3
> Unhandled exception. System.Exception: Could not determine compression used by partition mmcblk0p1 in: E:\MyFiles\CloneZilla\
>    at libClonezilla.PartitionContainers.ClonezillaImage.GetCompressionInUse(String clonezillaArchiveFolder, String partitionName)
>    at libClonezilla.PartitionContainers.ClonezillaImage.<>c__DisplayClass3_0.<.ctor>b__2(String partitionName)
>    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
>    at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable )+MoveNext()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 )
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
>    at libClonezilla.PartitionContainers.ClonezillaImage..ctor(String clonezillaArchiveFolder, IClonezillaCacheManager cacheManager, List`1 partitionsToLoad, Boolean willPerformRandomSeeking)
>    at libClonezilla.PartitionContainers.PartitionContainer.FromPath(String path, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
>    at libClonezilla.PartitionContainers.PartitionContainer.<>c__DisplayClass8_0.<FromPaths>b__0(String path)
>    at System.Linq.Enumerable.SelectListIterator`2.ToList()
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
>    at libClonezilla.PartitionContainers.PartitionContainer.FromPaths(List`1 paths, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
>    at clonezilla_util.Program.ExtractPartitionImage(ExtractPartitionImage extractPartitionImageOptions)
>    at clonezilla_util.Program.Run(Object obj)
>    at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
>    at clonezilla_util.Program.Main(String[] args)

**Comment by fiddyschmitt** [comment]
Thanks @swm123456, I'll fix that up :)

**Comment by fiddyschmitt** [comment]
Hi @swm123456, new version is up. Please let me know if it works :)

https://github.com/fiddyschmitt/clonezilla-util/releases/tag/v1.5.4

Cheers,
Fidel
