### ISSUE TITLE
Mounted partition is empty

### ISSUE THREAD

**Issue by johentsch** [fiddyschmitt/clonezilla-util#44]
Use the command `clonezilla-util.exe mount --input <clonzilla folder> --mount L:\` from the README (not being a Windows user I had to figure out first that I need to write `.\clonezilla-util.exe`). 

Everything looks like working perfectly:
![image](https://github.com/fiddyschmitt/clonezilla-util/assets/42718519/56788846-0442-4a7e-ac0f-997719e816b5)
The new drive shows up alright:
![image](https://github.com/fiddyschmitt/clonezilla-util/assets/42718519/3595ffb5-51a4-49c3-bcf4-38cdf55e5486)
But unfortunately it does not contain any files when I open it: "This folder is empty". Is this a known issue?

**Comment by johentsch** [comment]
(The shell is still showing a lot of CPU activity -- maybe I just need to wait a bit longer?)

**Comment by drequeary** [comment]
I had a similar problem. It was stuck at retrieving files. I re-installed using the 64msi installer.

**Comment by fiddyschmitt** [comment]
Thanks Johannes, when 7zFM.exe is chosen it uses the virtual drive (L:\) to unpack files, so yes I suspect it just needed more time.
