### ISSUE TITLE
Issue when listing or copying files: lib7Zip.UI.ListviewNative.GetRowText()

### ISSUE THREAD

**Issue by Marcel2508** [fiddyschmitt/clonezilla-util#7]
Hey, I used this tool to open a partition from a backup.
This worked fine so far and I was able to view it's contents.
However when I tried to search for a specific file and tried to copy it I'm constantly getting the following error shown in console, until windows says (after some time) that the copy process wasn't successfull and had to be aborted due to not enought system ressources (which is not the case..):

```
Error while navigating to 
L:\ddsfds-924c-4d9b-dgdg-sdfdfds- 
Temp\dfgdf-ab1f-4817-8867-gdfgdfdgfdgf\sda4.img\Users\XXXXX\Downloads\XXXXX.xxx: 
System.ArgumentOutOfRangeException: Length cannot be less than zero. 
(Parameter 'length')
    at System.String.Substring(Int32 startIndex, Int32 length)
    at lib7Zip.UI.ListviewNative.GetRowText(Int32 rowIndex, Int32 
columnIndex)
    at System.Linq.Enumerable.SelectRangeIterator`1.ToList()
    at System.Linq.Enumerable.SelectRangeIterator`1.ToList()
    at lib7Zip.UI.ListviewNative.GetRowData()
    at lib7Zip.UI.ListviewNative.GetRows()
    at lib7Zip.SevenZipExtractorUsing7zFM.NavigateToFilename(Int32 pid, 
IntPtr hWndFM, Nullable`1 desktopHandle, String fullFilename)
```

Any Idea what could be the issue?

Thanks in advance!

**Comment by fiddyschmitt** [comment]
Hi Marcel,

Thanks for reporting this :)

In the background, the application sometimes uses `7z.exe` (reliable but slow) and sometimes `7zFM.exe` (faster but unreliable in certain cases such as searching). It chooses which one based on how quickly it can seek around the archive, which is more to do with the compression format than the speed of your computer.

Could you please run the program with `mount-as-image-files` instead? You can then open those image files using 7-Zip. You can get a file list using the `list` command. A little clunky but hopefully it's useful.

Alternatively, you could extract the image file using `extract-partition-image`, then use the `mount` command on the extracted image and it should work better.

Please let me know how it goes :)
Fidel
